import getters from "./getters.js";
import mutations from "./mutations.js";
import actions from "./actions.js";

export default {
  namespaced: true,
  state: {
    FileModal: false,
    processing: false,
    fileSelected: false,
    fileUploading: false,
    button: "",
    isActive: true,
    typeOptions: [],
    fileMediaOptions: [],
    coverageTypeOptions: [],
    timeToneOptions: [],
    reqStatusOptions: [],
    MetaModalTitle: "",
    localFiles: [],
    uploaderCustomData: {},
    date: "",
    tempDate: "",
    fileSDate: "",
    tempFileSDate: "",
    fileEDate: "",
    tempFileEDate: "",
    scrRange: [],
    MetaData: {
      title: "",
      memo: "",
      reporter: "",
      proType: "",
      proTypeName: "",
      advertiser: "",
      mediaCD: "",
      categoryCD: "",
      typeSelected: "null",
      mediaSelected: "A",
      coverageTypeSelected: "RC07",
      mediaName: "",
      timeToneSelected: "TU",
      reqStatusSelected: "R",
      duration: "",
      audioFormat: "",
    },
    userProgramList: [],
    masteringListData: [],
    masteringLogData: [],
    ProgramData: [
      {
        eventName: "",
        eventType: "",
        productId: "",
        onairTime: "",
        durationSec: "",
      },
    ],
    ProgramSelected: {
      eventName: "",
      eventType: "",
      productId: "",
      onairTime: "",
      durationSec: "",
    },
    programState: false,
    EventData: [
      {
        name: "",
        id: "",
        duration: "",
      },
    ],
    EventSelected: {
      id: "",
      name: "",
      duration: "",
    },
    FileUploadProgress: {},
  },
  getters,
  mutations,
  actions,
};
